### ISSUE TITLE
Failed to activate the caniuse-css package

### ISSUE THREAD

**Issue by caseykdavis** [myJSheart/caniuse-css#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0-beta0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [caniuse-css](https://github.com/myJSheart/caniuse-css) package 1.1.5

### Stack Trace

Failed to activate the caniuse-css package

```
At Cannot read property 'onDidChangeCursorPosition' of undefined

TypeError: Cannot read property 'onDidChangeCursorPosition' of undefined
    at Object.activate (/packages/caniuse-css/lib/caniuse-css.js:38:34)
    at Package.module.exports.Package.activateNow (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/package.js:984:31
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:353:24)
    at CommandRegistry.dispatch (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:266:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom Beta.app/Contents/Resources/app/src/atom-environment.js:1348:34)
    at EventEmitter.outerCallback (/Applications/Atom Beta.app/Contents/Resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:09.4.0 caniuse-css:toggle (atom-pane.pane.active)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-bootstrap3 1.2.12 
atom-css-clean 2.23.0 
atom-ide-ui 0.3.1 
atom-laravel-snippets 0.2.0 
Atom-Syntax-highlighting-for-Sass 0.5.0 
autoclose-html 0.23.0 
autocomplete-font-awesome 0.2.1 
autocomplete-jquery-mobile 0.2.2 
autocomplete-paths 2.11.0 
bem-levels 1.0.1 
bemhtml 0.11.0 
blade-snippets 0.2.0 
bootstrap-3-snippetset 0.0.6 
bootstrap-sass-snippets 2.1.1 
busy-signal 1.4.3 
caniuse-css 1.1.5 
cdn-libs 0.1.2 
click-link 1.0.11 
color-picker 2.2.5 
color-tabs 0.1.8 
css-snippets 1.1.0 
file-icons 2.1.11 
font-awesome-snippetset 0.0.6 
gulp-control 0.5.0 
html-head-snippets 0.2.0 
ide-json 0.1.0 
ide-php 0.6.2 
ide-typescript 0.6.1 
img-placeholder 2.0.1 
intentions 1.1.5 
jQuery 1.2.5 
jquery-snippets 11.0.0 
language-blade 0.34.0 
laravel 0.7.1 
linter 2.0.0 
linter-bootlint 1.1.0 
linter-csslint 2.0.0 
linter-scss-lint 3.1.1 
linter-ui-default 1.6.8 
open-html-in-browser 0.2.0 
php-debug 0.2.5 
php-integrator-autocomplete-plus 1.6.0 
project-plus 1.0.0 
Remote-FTP 1.1.3 
terminal-plus 0.14.5 
```

**Comment by othersmallcities** [comment]
+1
